FROM node:20-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

# Copy source files
COPY . .

# Build the application
RUN npm run build

# Start dev server
CMD ["npm", "run", "start:dev"]
